#!/usr/bin/bash

set -Eeuo pipefail

install_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

for stage in dependencies binaries icons configs configs-system configs-account configs-post git-config services; do
  echo "==> $stage"
  "$install_dir/$stage"
done