#!/usr/bin/bash

set -Eeuo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

answer="$(ask 'Add your user to device groups (video, docker, lp)? [Y/n] ')"
case $answer in
  [Yy]* | "")
    run sudo usermod -aG video "$USER"
    run sudo usermod -aG docker "$USER"
    run sudo usermod -aG lp "$USER" # printer group
    ;;
  * ) ;;
esac

answer="$(ask "Set your login shell to zsh? [Y/n] ")"
case $answer in
  [Yy]* | "")
    run chsh -s /usr/bin/zsh
    ;;
  * ) ;;
esac
