#!/usr/bin/bash

set -Eeuo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

run xset dpms 1200 0 0

run fc-cache -r
run tldr -u
run sudo mandb

answer="$(ask 'Set system timezone to CET? [Y/n] ')"
case $answer in
  [Yy]* | "")
    run timedatectl set-timezone CET
    ;;
  * ) ;;
esac