#!/usr/bin/bash

set -Eeuo pipefail

xset dpms 1200 0 0

fc-cache -r
tldr -u
sudo mandb

read -rp 'Set system timezone to CET? [Y/n] ' answer
case $answer in
  [Yy]* | "")
    timedatectl set-timezone CET
    ;;
  * ) ;;
esac