#!/usr/bin/bash

set -Eeuo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

mapfile -t groups < <(manifest_package_groups ".common.packages, .profiles.$INSTALL_PROFILE.packages" | sort -u)
for group in "${groups[@]}"; do
  run sudo usermod -aG "$group" "$USER"
done

answer="$(ask "Set your login shell to zsh? [Y/n] ")"
case $answer in
  [Yy]* | "")
    run chsh -s /usr/bin/zsh
    ;;
  * ) ;;
esac
