#!/usr/bin/bash

set -Eeuo pipefail

install_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$install_dir/common.sh"
source "$HOME/dotfiles/linux/variables.env"
source "$install_dir/config-links.sh"

run mkdir -p "$XDG_CONFIG_HOME"
run mkdir -p "$HOME/.ssh"

link_config "$DOT_CONFIG/zsh/zshrc" "$HOME/.zshrc"
link_config "$DOT_CONFIG/nvim" "$XDG_CONFIG_HOME/nvim"
link_config "$DOT_CONFIG/opencode" "$XDG_CONFIG_HOME/opencode"
