#!/usr/bin/bash

set -Eeuo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh" "$@"
source "$DOTFILES/linux/variables.env"

# The user icon theme (icons/*) is linked by dotpkg as a manifest resource;
# only the root-owned Font Awesome icon sets stay imperative.

run sudo mkdir -p "/usr/share/icons/FontAwesome-6/solid/512x512/"
run sudo mkdir -p "/usr/share/icons/FontAwesome-6/brands/512x512/"
run sudo rm -rf "/usr/share/icons/FontAwesome-6/solid/512x512/all"
run sudo rm -rf "/usr/share/icons/FontAwesome-6/brands/512x512/all"
run sudo ln -fvs "$DOTFILES/fonts/fa6/pngs/solid" "/usr/share/icons/FontAwesome-6/solid/512x512/all"
run sudo ln -fvs "$DOTFILES/fonts/fa6/pngs/brands" "/usr/share/icons/FontAwesome-6/brands/512x512/all"
