#!/usr/bin/bash

set -eu

source "$HOME/dotfiles/linux/variables.env"

mkdir -p "$HOME/.local/share/icons"

icon_sets=$(find "$DOTFILES/icons/" -maxdepth 1 -type d | tail -n +2)

for set in $icon_sets; do
  destination="$HOME/.local/share/icons/$(basename $set)"
  rm -vrf "$destination"

  sudo ln -fvs "$set" "$destination"
done

sudo mkdir -p "/usr/share/icons/FontAwesome-6/solid/512x512/"
sudo mkdir -p "/usr/share/icons/FontAwesome-6/brands/512x512/"
sudo rm -rf "/usr/share/icons/FontAwesome-6/solid/512x512/all"
sudo rm -rf "/usr/share/icons/FontAwesome-6/brands/512x512/all"
sudo ln -fvs "$DOTFILES/fonts/fa6/pngs/solid" "/usr/share/icons/FontAwesome-6/solid/512x512/all"
sudo ln -fvs "$DOTFILES/fonts/fa6/pngs/brands" "/usr/share/icons/FontAwesome-6/brands/512x512/all"
