#!/usr/bin/bash

source "$HOME/dotfiles/linux/variables"

systemctl enable --now docker ly bluetooth NetworkManager avahi-daemon cups

systemctl --user enable --now "$DOTFILES/linux/config/polybar/polybar.service"
systemctl --user enable --now "$DOTFILES/linux/config/wired/wired.service"
