#!/usr/bin/bash

set -Eeuo pipefail

build_dir="$(mktemp -d)"
trap 'rm -rf "$build_dir"' EXIT

git clone https://aur.archlinux.org/yay-git.git "$build_dir/yay-git"
cd "$build_dir/yay-git"

makepkg -si

rm -rf "$build_dir"
