#!/usr/bin/bash

# Editor
alias vim="nvim"

# Bash
alias open="xdg-open"
alias o="xdg-open"
alias v="viewnior"
alias t="tree"
alias cls="printf '\033c'"

if [[ $(which bat) ]] ; then
  alias b="bat"
elif [[ $(which batcat) ]]; then
  alias b="batcat"
  alias bat="batcat"
fi

[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"
