#!/usr/bin/bash

# Editor
alias vim="nvim"

# Bash
alias open="xdg-open"
alias o="xdg-open"
alias v="viewnior"
alias t="tree"
alias cls="printf '\033c'"
alias b="bat"

[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"
