#!/usr/bin/env sh

rm -rf ~/.config/rofi/config.rasi ~/.Xmodmap
rm -rf ~/.i3/config ~/.profile ~/.Xresources

mkdir ~/screenshots

mkdir -p ~/.i3
ln -fvs ~/dotfiles/linux/i3/config ~/.i3/config

mkdir -p ~/.config/rofi
ln -fvs ~/dotfiles/linux/rofi.rasi ~/.config/rofi/config.rasi

mkdir -p ~/.config/nvim
ln -fvs ~/dotfiles/linux/neo.vim ~/.config/nvim/init.vim

mkdir -p ~/.config/gsimplecal
ln -fvs ~/dotfiles/linux/config/gsimplecal ~/.config/gsimplecal/config

mkdir -p ~/.config/dunst
ln -fvs ~/dotfiles/linux/config/dunst ~/.config/dunst/dunstrc

ln -fvs ~/dotfiles/linux/Xresources ~/.Xresources
ln -fvs ~/dotfiles/linux/profile ~/.profile
ln -fvs ~/dotfiles/linux/xprofile ~/.xprofile
ln -fvs ~/dotfiles/linux/keys.map ~/.Xmodmap
ln -fvs ~/dotfiles/linux/config/picom.conf ~/.config/picom.conf
sudo ln -fvs ~/dotfiles/linux/devices/30-touchpad.conf /etc/X11/xorg.conf.d/30-touchpad.conf
sudo ln -fvs ~/dotfiles/linux/peripherals/$(hostname).conf /etc/X11/xorg.conf
sudo ln -fvs ~/dotfiles/linux/scripts/exit /usr/bin/i3exit

sudo ln -fvs ~/dotfiles/linux/udev/usb-watcher.rules /usr/lib/udev/rules.d/5-usb-watcher.rules
sudo cp -f ~/dotfiles/linux/config/sudoers.d/20-custom-rules /etc/sudoers.d/20-custom-rules

ln -fvs ~/dotfiles/linux/config/default-apps.list ~/.local/share/applications/defaults.list

sudo rmmod pcspkr
