#!/usr/bin/env sh

install_pulse

pamac install ttf-hack noto-fonts-cjk
pamac install polybar neovim neovide thefuck bat tldr dunst-git
pamac install zsh zsh-completions rofi rofi-bluetooth-git xdo
pamac install autorandr xclip i3lock-fancy-dualmonitor-git
pamac install dropbox flameshot timeshift etcher 1password
pamac install sysstat xdotool gconf cmake jq light vlc
pamac install xwallpaper sxiv playerctl unzip unrar ctags
pamac install rubygems nvm the_silver_searcher diff-so-fancy
pamac install pantheon-calculator gsimplecal zeal spotify
pamac install nordvpn-bin google-chrome pulseaudio-bluetooth
pamac install postgresql-10 redis docker docker-compose woeusb
pamac install slack-desktop whatsapp-nativefier telegram-desktop
pamac install via-bin stress librecad avr-gcc dfu-programmer avrdude
pamac install gcc-arm-none-eabi-bin bootloadhid imagemagick-full neofetch

pamac remove palemoon-bin
