#!/usr/bin/bash

set -e

sudo pacman -S --noconfirm i3-wm picom rofi ibus inetutils openssh polkit polkit-gnome xfce4-power-manager network-manager-applet man-db wget ttf-hack noto-fonts-cjk polybar bc xwallpaper ddcutil zsh zsh-completions xdo light autorandr sysstat xdotool cmake jq sxhkd xautolock imagemagick i3lock blueman flameshot vlc birdfont unzip unrar fragments sxiv playerctl pantheon-calculator gsimplecal curtail blanket xclip neofetch tree v4l-utils rubygems npm neovim neovide kitty ctags bat tldr docker docker-compose the_silver_searcher diff-so-fancy telegram-desktop pipewire-jack pipewire-alsa pipewire-pulse qjackctl
sudo pacman -Sc

source ./yay

yay -S --noconfirm eww-git dropbox wired oh-my-zsh google-chrome 1password spotify slack-desktop zeal
sudo yay -Sc
