#!/usr/bin/bash

set -e

git clone https://github.com/elkowar/eww
cd eww

curl https://sh.rustup.rs -sSf | sh
sudo apt-get install -y pkg-config libgtk-3-dev

cargo build --release

cd target/release
chmod +x ./eww
sudo cp ./eww /usr/local/bin/
