#!/usr/bin/bash

set -e

repo_location=~/wired-notify

sudo apt-get install -y libxss-dev

git clone git@github.com:Toqozz/wired-notify.git $repo_location

cd $repo_location
cargo build --release

sudo cp ./target/release/wired /usr/local/bin
chmod +x /usr/local/bin/wired

rm -rf $repo_location
