#!/usr/bin/bash

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nm-applet &
dropbox start -i &
xss-lock --transfer-sleep-lock -- u_exit lock &
flameshot &
1password --silent &
greenclip daemon &
sxhkd -c "$HOME/dotfiles/linux/config/sxhkdrc" &
kmonad "$HOME/dotfiles/linux/config/kmonad.kbd" &
u_i3-workspaces &
