#!/usr/bin/bash

if ! [ -x "$(command -v brew)" ]; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew install ctags the_silver_searcher tldr bat \
             vim neovim zsh zsh-completions tree \
             diff-so-fancy jq imagemagik

brew install --cask vlc google-chrome slack \
             vlc spectacle

curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
