#!/usr/bin/env sh

# Editor
alias e="nvim ."
alias vim="nvim"

# GIT
alias g="git"
alias gs="git status"
alias gd="git diff --color"
alias ga="git add"
alias gal="git add ."
alias gb="git branch --sort committerdate"
alias gc="git checkout"
alias gcb="git checkout -b"
alias gcl="git clone --recursive"
alias gmv="git mv"
alias gcm="git commit"
alias gcmf="git commit --fixup"
alias gcam="git add . && git commit"
alias gcamf="git add . && git commit --fixup"
alias gps="git push"
alias gpl="git pull --rebase"
alias gm="git merge"
alias gr="git rebase"
alias gri="git rebase -i --autosquash"
alias grhh="git reset --hard HEAD"
alias gl="git log"
alias gls="git log --oneline --decorate"
alias grl="git reflog"
alias gcap="git add . && git commit --amend --no-edit && git push --force-with-lease"

function clean_branches() {
  git branch --merged master | grep -v master | xargs git branch -d
}

# Docker
alias dc="docker"
alias dcp="docker-compose"

# Linux
alias cls="printf '\033c'"
