#!/usr/bin/env sh

rm -rf ~/.bash_profile ~/.bashrc ~/.vimrc ~/.zshrc

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

curl -L get.rvm.io | bash -s stable
curl -L http://install.ohmyz.sh | sh

ln -fvs ~/dotfiles/rcs/vimrc ~/.vimrc
ln -fvs ~/dotfiles/rcs/zshrc ~/.zshrc

mkdir -v ~/backup_vim
