#!/usr/bin/env sh

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

curl -L get.rvm.io | bash -s stable
curl -L http://install.ohmyz.sh | sh
