#!/usr/bin/bash

git config --global user.email "the.lukelex@gmail.com"
git config --global user.name "Lukas Alexandre"

git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
git config --global color.ui true

git config --global color.diff-highlight.oldNormal    "red bold"
git config --global color.diff-highlight.oldHighlight "red bold 52"
git config --global color.diff-highlight.newNormal    "green bold"
git config --global color.diff-highlight.newHighlight "green bold 22"

git config --global color.diff.meta       "yellow"
git config --global color.diff.frag       "magenta bold"
git config --global color.diff.commit     "yellow bold"
git config --global color.diff.old        "red bold"
git config --global color.diff.new        "green bold"
git config --global color.diff.whitespace "red reverse"

git config --global rebase.autosquash true
git config --global push.default current
git config --global pull.rebase true

git config --global core.excludesfile ~/dotfiles/unix/gitignore
