#!/bin/bash

toggle_bluetooth() {
  if [[ $(bluetooth | awk '{ print $3 }') == 'on' ]]; then
    bluetooth off > /dev/null
  else
    bluetooth on > /dev/null
  fi
}

case $BLOCK_BUTTON in
  1) toggle_bluetooth ;;
  3) bluetooth on && blueman-manager > /dev/null ;;
esac

if [[ $(bluetooth | awk '{ print $3 }') == 'off' ]]; then
  echo ""
else
  echo ""
fi
