#!/bin/bash

enable_sleep() {
  gsettings set org.gnome.desktop.session idle-delay 300
  xautolock -enable
}

disable_sleep() {
  gsettings set org.gnome.desktop.session idle-delay 0
  xautolock -disable
}

case $BLOCK_BUTTON in
  1) enable_sleep ;;
  3) disable_sleep ;;
esac

if [[ $(gsettings get org.gnome.desktop.session idle-delay | cut -c8-) -eq 0 ]]; then
  echo ""
else
  echo ""
fi
