#!/bin/bash

INTERFACE=$(iw dev | awk '$1=="Interface"{print $2}')

[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
  [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

echo $QUALITY% # full text
echo $QUALITY% # short text

# color
if [[ $QUALITY -ge 80 ]]; then
  echo "#00FF00"
elif [[ $QUALITY -ge 60 ]]; then
  echo "#FFF600"
elif [[ $QUALITY -ge 40 ]]; then
  echo "#FFAE00"
else
  echo "#FF0000"
fi
