# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="robbyrussell"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# source $(brew --prefix nvm)/nvm.sh

source ~/dotfiles/unix/aliases.sh
source ~/dotfiles/unix/env.sh
if [[ "$(uname)" == 'Linux' ]]; then
  source ~/dotfiles/linux/env.sh
else
  source ~/dotfiles/osx/env.sh
fi
