# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="robbyrussell"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# source $(brew --prefix nvm)/nvm.sh

source ~/dotfiles/aliases.sh
source ~/dotfiles/unix/env.sh
if [[ "$(uname)" == 'Linux' ]]; then
  source ~/dotfiles/linux/env.sh
else
  source ~/dotfiles/osx/env.sh
fi
