#!/bin/bash

function turn_on {
  amixer -D pulse set Master on > /dev/null
}

function get {
  amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
  amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function show {
  volume=`get`

  dunstify -i notification-audio-volume-high \
           -r 12 \
           -u low \
           -a Volume \
           -h int:value:"$volume" \
           "unused"
}

case $1 in
  mic)
    case $2 in
      toggle)
        echo 'toggling mic'
        ;;
    esac
    ;;
  vol)
    case $2 in
      inc)
        turn_on
        amixer -D pulse sset Master 1%+ > /dev/null
        show
        ;;
      dec)
        turn_on
        amixer -D pulse sset Master 1%- > /dev/null
        show
        ;;
      show) show ;;
      toggle)
        amixer -D pulse set Master 1+ toggle > /dev/null
        if is_mute ; then
          dunstify -i notification-audio-volume-muted \
                   -r 12 \
                   -u low \
                   -a Volume \
                   "0%" "Mute"
        else
          show
        fi
        ;;
    esac
esac
