#!/usr/bin/bash

set -eu

source "$HOME/dotfiles/linux/variables.env"

VOL_HIGH=$(printf "\ue1ab")
VOL_MEDIUM=$(printf "\ue1ab")
VOL_LOW=$(printf "\ue1aa")
VOL_MUTE=$(printf "\ue1ac")

MIC_HIGH=$(printf "\ue724")
MIC_MEDIUM=$(printf "\ue118")
MIC_LOW=$(printf "\ue118")
MIC_MUTE=$(printf "\ue119")

function icon_mic {
  value=$(get_mic)

  if mic_is_mute; then
    echo $MIC_MUTE
  elif [[ 1 -eq $(echo "$value > 85" | bc -l) ]]; then
    echo "%{F#FF0000}$MIC_HIGH%{F-}"
  elif [[ 1 -eq $(echo "$value > 50" | bc -l) ]]; then
    echo $MIC_HIGH
  elif [[ 1 -eq $(echo "$value > 25" | bc -l) ]]; then
    echo $MIC_MEDIUM
  else
    echo $MIC_LOW
  fi
}

function icon_volume {
  value=$(get_volume)

  if [[ $(vol_is_mute) ]]; then
    echo $VOL_MUTE
  elif [[ 1 -eq $(echo "$value > 85" | bc -l) ]]; then
    echo $VOL_HIGH
  elif [[ 1 -eq $(echo "$value > 50" | bc -l) ]]; then
    echo $VOL_HIGH
  elif [[ 1 -eq $(echo "$value > 25" | bc -l) ]]; then
    echo $VOL_MEDIUM
  else
    echo $VOL_LOW
  fi
}

function get_volume {
  bc <<< "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}') * 100"
}

function get_mic {
  bc <<< "$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | awk '{print $2}') * 100"
}

function vol_is_mute {
  pactl get-sink-mute @DEFAULT_SINK@ | grep yes
}

function mic_is_mute {
  wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | grep -q MUTED
}

function show_volume {
  volume=$(get_volume)

  if vol_is_mute ; then
    notify-send -a System \
      -i "$LUCIDE_PATH/volume-x.svg" \
      -h string:wired-tag:system \
      -h int:value:0\
      "Volume" 2> /dev/null || true
  elif [[ 1 -eq $(echo "$volume > 50" | bc -l) ]]; then
    notify-send -a System \
      -i "$LUCIDE_PATH/volume-2.svg" \
      -h string:wired-tag:system \
      -h int:value:"$volume" \
      "Volume" 2> /dev/null || true
  elif [[ 1 -eq $(echo "$volume > 25" | bc -l) ]]; then
    notify-send -a System \
      -i "$LUCIDE_PATH/volume-1.svg" \
      -h string:wired-tag:system \
      -h int:value:"$volume" \
      "Volume" 2> /dev/null || true
  else
    notify-send -a System \
      -i "$LUCIDE_PATH/volume.svg" \
      -h string:wired-tag:system \
      -h int:value:"$volume" \
      "Volume" 2> /dev/null || true
  fi
}

function show_mic {
  volume=$(get_mic)

  if mic_is_mute ; then
    notify-send -a System \
      -i "$LUCIDE_PATH/mic-off.svg" \
      -h string:wired-tag:system \
      -h int:value:0\
      "Microphone" 2> /dev/null || true
  else
    notify-send -a System \
      -i "$LUCIDE_PATH/mic-audio-lines.svg" \
      -h string:wired-tag:system \
      -h int:value:"$volume" \
      "Microphone" 2> /dev/null || true
  fi
}

case $1 in
  mic|microphone)
    case $2 in
      get) get_mic ;;
      icon) icon_mic ;;
      set)
        mic=$(echo "$3" | awk '{if ($1 > 100) print 100; else if ($1 < 0) print 0; else print $1}')
        wpctl set-volume @DEFAULT_AUDIO_SOURCE@ "$mic%"
        # show_mic
        ;;
      inc)
        mic=$(awk -v current="$(get_mic)" 'BEGIN { print (current > 98 ? 100 : current + 2) }')
        wpctl set-volume @DEFAULT_AUDIO_SOURCE@ "$mic%"
        ;;
      dec)
        wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 2%-
        ;;
      show) show_mic ;;
      toggle)
        wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
        ;;
    esac
    ;;
  vol|volume)
    case $2 in
      get) get_volume ;;
      icon) icon_volume ;;
      inc)
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+ ;;
      dec)
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%- ;;
      set)
        vol=$(echo "$3" | awk '{if ($1 > 100) print 100; else if ($1 < 0) print 0; else print $1}')
        wpctl set-volume @DEFAULT_AUDIO_SINK@ "$vol%"
        # show_volume
        ;;
      show) show_volume ;;
      default) wpctl set-default "$3" ;;
      toggle)
        wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle ;;
    esac
esac
