#!/usr/bin/bash

set -eu

source "$HOME/dotfiles/linux/variables.env"

function show_warning {
  case "$XDG_SESSION_TYPE" in
    x11|wayland) notify-send -a System \
        -i "$LUCIDE_PATH/alarm-clock.svg" \
        -h string:wired-tag:lock-warning \
        -t 0 \
        "Screen will lock in $1 seconds" ;;
  esac
}

function clear_warning {
  qs -p "$HOME/dotfiles/linux/config/quickshell/shell.qml" \
    ipc call notifications dismissTag lock-warning 2> /dev/null || true
}

function should_lock {
  local window_id
  local fullscreen_window

  window_id=$(xprop -root | grep "_NET_ACTIVE_WINDOW" | head -n 1 | awk '{print $5}')
  fullscreen_window=$(xprop -id "$window_id" 2> /dev/null | grep -E "_NET_WM_STATE\(ATOM\).+?_NET_WM_STATE_FULLSCREEN" || true)

  if [[ -z $fullscreen_window ]]; then
    echo "yes"
  fi
}

case $1 in
  warn) show_warning "$2" ;;
  clear-warning) clear_warning ;;
  lock) [ ! -z "$(should_lock)" ] && u_exit lock ;;
  *) exit 0 ;;
esac
