#!/bin/bash

case $1 in
  inc)
    sudo light -A 2
    $($0 show)
    ;;
  dec)
    sudo light -U 2
    $($0 show)
    ;;
  show)
    brightness=$(light -G | cut -f1 -d".")

    dunstify -i sunflower \
             -r 6 \
             -u low \
             -a Backlight \
             -h int:value:"$brightness" \
             "unused"
    ;;
esac
