#!/bin/bash

case $1 in
  inc)
    xbacklight -inc 5%
    $($0 show)
    ;;
  dec)
    xbacklight -dec 5%
    $($0 show)
    ;;
  show)
    dunstify -r 2 -t 1000 -i sunflower "Backlight" $(xbacklight -get | cut -f1 -d".")%
    ;;
esac
