#!/bin/bash

HIGH=
LOW=
VALUE=$(light -G | cut -f1 -d".")

case $1 in
  if)
    light -L 2>&- | grep monitor
    ;;
  icon)
    if [[ 1 -eq $(echo "$VALUE > 75" | bc -l) ]]; then
      echo "%{F#FF0000}$HIGH%{F-}"
    elif [[ 1 -eq $(echo "$VALUE > 25" | bc -l) ]]; then
      echo $HIGH
    else
      echo $LOW
    fi
    ;;
  inc)
    light -A 2 2>&-
    $($0 show)
    ;;
  dec)
    light -U 2 2>&-
    $($0 show)
    ;;
  show)
    dunstify -i sunflower \
             -r 6 \
             -u low \
             -a Backlight \
             -h int:value:"$VALUE" \
             "unused"
    ;;
esac
