#!/bin/bash

stats=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "state|to\ full|percentage|time\ to\ empty")
state=$(echo "$stats" | grep state | awk '{print $2}')
charge=$(echo "$stats" | grep percentage | awk '{print $2}')
time=$(echo "$stats" | grep time | awk '{print $4" "$5}')

echo "$stats"

if [ -z $time ]; then
  message="Fully charged!"
else
  message="$time left"
fi

notify-send -a Battery \
            -i ~/dotfiles/fonts/fa6/pngs/light/battery-full.png \
            -h string:wired-tag:app \
            -h int:value:"$charge" \
            "$message"
