#!/bin/bash

stats=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "state|to\ full|percentage|time\ to\ empty")
state=$(echo "$stats" | grep state | awk '{print $2}')
charge=$(echo "$stats" | grep percentage | awk '{print $2}')
time=$(echo "$stats" | grep time | awk '{print $4" "$5}')

echo "$stats"
dunstify -i battery-full \
         -r 11 \
         -u low \
         -a Battery \
         -h int:value:"$charge" \
         "blank" "$state. $time left"
