#!/usr/bin/bash

set -eu

source "$HOME/dotfiles/linux/variables.env"

CHARGING=$(printf "\ue054")
CRITICAL=$(printf "\ue3ac")
LOW=$(printf "\ue056")
QUARTER=$(printf "\ue056")
HALF=$(printf "\ue057")
THREE_QUARTERS=$(printf "\ue057")
FULL=$(printf "\ue055")
LOW_BATTERY_THRESHOLD=15
LOW_BATTERY_NOTIFICATION_FILE="${XDG_CACHE_HOME:-$HOME/.cache}/battery-low-notified"

device=$(upower -e | grep 'BAT' | head -n 1)
stats=$(upower -i "$(echo $device)" | grep -E "state|to full|percentage|time to empty")

get_percentage() {
  echo "$stats" | grep percentage | awk '{print $2}' | sed 's/%//'
}

get_state() {
  echo "$stats" | grep state | awk '{print $2}'
}

is_charging() {
  [[ "$(get_state)" == charging ]]
}

icon() {
  value=$(get_percentage)

  if is_charging; then
    echo $CHARGING
  elif [[ 1 -eq $(echo "$value < 6" | bc -l) ]]; then
    echo "%{F#FF0000}$CRITICAL%{F-}"
  elif [[ 1 -eq $(echo "$value < 16" | bc -l) ]]; then
    echo $LOW
  elif [[ 1 -eq $(echo "$value < 26" | bc -l) ]]; then
    echo $QUARTER
  elif [[ 1 -eq $(echo "$value < 51" | bc -l) ]]; then
    echo $HALF
  elif [[ 1 -eq $(echo "$value < 91" | bc -l) ]]; then
    echo $THREE_QUARTERS
  else
    echo $FULL
  fi
}

notification_icon() {
  local value

  value=$(get_percentage)

  if is_charging; then
    echo "$LUCIDE_PATH/battery-charging.svg"
  elif [[ $value -lt 6 ]]; then
    echo "$LUCIDE_PATH/battery-warning.svg"
  elif [[ $value -lt 26 ]]; then
    echo "$LUCIDE_PATH/battery-low.svg"
  elif [[ $value -lt 51 ]]; then
    echo "$LUCIDE_PATH/battery-medium.svg"
  elif [[ $value -lt 91 ]]; then
    echo "$LUCIDE_PATH/battery.svg"
  else
    echo "$LUCIDE_PATH/battery-full.svg"
  fi
}

get() {
  state=$(echo "$stats" | grep state | awk '{print $2}')
  charge=$(echo "$stats" | grep percentage | awk '{print $2}')
  time=$(echo "$stats" | grep time | awk '{print $4" "$5}')

  echo "$state | $charge | $time"
}

shorten_time() {
  case "$1" in
    *hours)   echo "${1% hours} hr" ;;
    *minutes) echo "${1% minutes} min" ;;
    *seconds) echo "${1% seconds} sec" ;;
    *)        echo "$1 left" ;;
  esac
}

show_battery() {
  local charge
  local time
  local notification_icon

  charge=$(get_percentage)
  time=$(echo "$stats" | grep time | awk '{print $4" "$5}')
  notification_icon=$(notification_icon)

  if [[ -z $time ]]; then
    message="Full"
  else
    message=$(shorten_time "$time")
  fi

  notify-send -a System \
    -i "$notification_icon" \
    -h string:wired-tag:system \
    -h int:value:"$charge" \
    "$message"
}

warn() {
  local state
  local charge

  state=$(get_state)
  charge=$(get_percentage)

  if [[ $state == discharging && $charge -le $LOW_BATTERY_THRESHOLD ]]; then
    if [[ ! -e $LOW_BATTERY_NOTIFICATION_FILE ]]; then
      mkdir -p "$(dirname "$LOW_BATTERY_NOTIFICATION_FILE")"
      notify-send -a System \
        -i "$LUCIDE_PATH/battery-low.svg" \
        -h string:wired-tag:battery-low \
        -h int:value:"$charge" \
        "Battery low" "$charge% remaining"
      : > "$LOW_BATTERY_NOTIFICATION_FILE"
    fi
  else
    rm -f "$LOW_BATTERY_NOTIFICATION_FILE"
  fi
}

case $1 in
  if) upower -i "$(upower -e | grep 'BAT')" ;;
  icon) echo "$(icon)" ;;
  show) show_battery ;;
  icon_and_warn) warn && icon ;;
  get) echo -e "$(get)" ;;
esac
