#!/bin/sh

info=$(bluetoothctl show)

powered=$(echo "$info" | grep 'Powered: yes' | xargs)
summary=$(bluetoothctl paired-devices | awk '{print $3 " (paired)"}')

notify-send -a Bluetooth \
            -i ~/dotfiles/fonts/fa6/pngs/brands/bluetooth.png \
            -h string:wired-tag:bluetooth \
            "$powered" "$summary"
