#!/usr/bin/bash

set -Eeuo pipefail

source "$HOME/dotfiles/linux/variables.env"

device_path=""
connected_property=0

notify_event() {
  local state="$1" address name icon type tag info
  address="${device_path##*/dev_}"
  address="${address//_/:}"
  info="$(bluetoothctl info "$address")"
  name="$(awk -F': ' '/Alias:/ { print $2; exit }' <<< "$info")"
  icon="$(awk -F': ' '/Icon:/ { print $2; exit }' <<< "$info")"
  name="${name:-Bluetooth device}"
  case "$icon" in
    input-mouse) type="Mouse"; icon="mouse" ;;
    input-keyboard) type="Keyboard"; icon="keyboard" ;;
    input-tablet) type="Tablet"; icon="tablet" ;;
    audio-card|audio-headset|audio-headphones) type="Audio device"; icon="headphones" ;;
    phone) type="Phone"; icon="smartphone" ;;
    computer) type="Computer"; icon="monitor" ;;
    *)
      type="Bluetooth device"
      if [ "$state" = connected ]; then
        icon="bluetooth-connected"
      else
        icon="bluetooth-off"
      fi
      ;;
  esac
  tag="bluetooth-${address//:/-}"

  printf 'bluetooth-notify: %s %s %s\n' "$state" "$type" "$name" >&2
  notify-send -a System \
    -i "$LUCIDE_PATH/$icon.svg" \
    -h "string:wired-tag:$tag" \
    -u low \
    -t 5000 \
    "Bluetooth device $state" "$type: $name" || true
}

stdbuf --output=L dbus-monitor --system \
  "type='signal',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',arg0='org.bluez.Device1'" |
  while IFS= read -r line; do
    case "$line" in
      signal\ *path=/org/bluez/*)
        device_path="${line#*path=}"
        device_path="${device_path%%;*}"
        connected_property=0
        ;;
      *'string "Connected"'*) connected_property=1 ;;
      *'boolean true'*)
        if [ "$connected_property" -eq 1 ] && [ -n "$device_path" ]; then
          notify_event connected
        fi
        connected_property=0
        ;;
      *'boolean false'*)
        if [ "$connected_property" -eq 1 ] && [ -n "$device_path" ]; then
          notify_event disconnected
        fi
        connected_property=0
        ;;
    esac
  done
