#!/bin/bash

core_temps=$(sensors | awk '/coretemp/' RS='\n\n' ORS='\n\n')

notify-send.py -i thermal-monitor \
               --replaces-process thermals \
               -t 3000 \
               "CPU Temperature" "$core_temps"
