#!/bin/bash

core_temps=$(sensors | awk '/coretemp/' RS='\n\n' ORS='\n\n')

notify-send -a CPU \
            -i /usr/share/icons/FontAwesome-6/light/512x512/all/temperature-list.png \
            -h string:wired-tag:cpu \
            "Temperature" "$core_temps"
