#!/bin/bash

grep -v "#" ~/dotfiles/unix/emoji | dmenu -i -l 20 -fn Monospace-18 | awk '{print $1}' | tr -d '\n' | xclip -selection clipboard

pgrep -x dunst >/dev/null &&
  dunstify -r 25 "$(xclip -o -selection clipboard) copied to clipboard"
