#!/usr/bin/bash

function reset_ui {
  u_music pause 2&> /dev/null
  u_eww close 2&> /dev/null
}

case "$1" in
  lock)
    reset_ui
    case "$XDG_SESSION_TYPE" in
      x11) u_blurlock ;;
      wayland) hyprlock ;;
    esac ;;
  logout)
    case "$XDG_SESSION_DESKTOP" in
      i3|i3wm) i3-msg exit ;;
      Hyprland) hyprctl dispatch exit 1 ;;
      *) loginctl terminate-session `loginctl session-status | awk 'NR==1{print $1}'` ;;
    esac ;;
  sleep|suspend)
    reset_ui
    $0 lock &
    systemctl suspend ;;
  hibernate)
    reset_ui && systemctl hibernate;;
  reboot|reset)
    systemctl reboot;;
  shutdown|poweroff)
    systemctl poweroff;;
  *)
    echo "== ! exit: missing or invalid argument ! =="
    echo "Try again with: lock | logout | suspend | hibernate | reboot | shutdown"
    exit 2
esac

exit 0
