#!/usr/bin/bash

u_music pause
u_eww close 2&> /dev/null

case "$1" in
  lock)
    u_blurlock
    ;;
  logout)
    i3-msg exit
    ;;
  switch_user)
    logout
    ;;
  suspend)
    u_exit lock && systemctl suspend
    ;;
  hibernate)
    u_exit lock && systemctl hibernate
    ;;
  reboot)
    systemctl reboot
    ;;
  shutdown)
    systemctl poweroff
    ;;
  *)
    echo "== ! exit: missing or invalid argument ! =="
    echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
    exit 2
esac

exit 0
