#!/bin/bash

version=$(uname -r)
node=$(uname -n)

notify-send -a Kernel \
            -i /usr/share/icons/FontAwesome-6/brands/512x512/all/linux.png \
            -h string:wired-tag:kernel \
            "$node" "$version"
