#!/usr/bin/bash

set -Eeuo pipefail

hour=$(date +%H)
case "$hour" in
  05|06|07|08|09|10|11) greeting="Good morning" ;;
  12|13|14|15|16|17) greeting="Good afternoon" ;;
  18|19|20|21) greeting="Good evening" ;;
  *) greeting="Good night" ;;
esac

printf '%s, %s\n' "$greeting" "${USER:-there}"
