#!/usr/bin/bash

source "$HOME/dotfiles/linux/variables.env"

get() {
  last_monitor=$(echo "$monitors" | grep -o .$)

  sudo ddcutil --bus="$last_monitor" getvcp "$feature" | grep -oP 'current\svalue\s*=\s*\K\d+'
}

set() {
  new_value="$1"

  if [ "$new_value" -le -1 ] || [ "$new_value" -ge 101 ]; then
    return 0
  fi

  IFS=$'\n'
  while read -r line
  do
    sudo ddcutil --bus="$line" setvcp "$feature" "$new_value" &> /dev/null &
  done < <(echo "$monitors")
}

show() {
  value=$1

  notify-send -a System \
    -i "$FONT_AWESOME_PATH/light/display.svg" \
    -h int:value:"$value" \
    -h string:wired-tag:system \
    "$feature_name"
}

case $1 in
  brightness)
    feature=10
    feature_name=$1
    ;;
esac

monitors=$(sudo ddcutil detect | grep "I2C bus" | grep -o .$)
step=5
current=$(get)
current=${current:-0}

case $2 in
  if) echo "$monitors" | grep 1 ;;
  get) echo "$current" ;;
  set)
    set "$3"
    show "$3"
    ;;
  inc)
    new_value=$(("$current" + "$step"))
    set "$new_value"
    show "$new_value"
    ;;
  dec)
    new_value=$(("$current" - "$step"))
    set "$new_value"
    show "$new_value"
    ;;
  reset)
    set 0
    show 0
    ;;
esac
