#!/usr/bin/bash

case $1 in
  previous)
    playerctl -p spotify previous &
    ;;
  next)
    playerctl -p spotify next &
    ;;
  pause)
    playerctl --all-players pause &
    ;;
  play)
    playerctl -p spotify play &
    ;;
  toggle)
    case $(playerctl --all-players status | grep "Playing" | head -n 1) in
      "Playing") playerctl --all-players pause ;;
      *) playerctl -p spotify play ;;
    esac
    ;;
esac