#!/usr/bin/bash

trim() {
  local text=$1
  local scale_rate=175
  local horizontal_size=$(xrandr | grep '*' | head -n 1 | cut -d 'x' -f 1 | xargs)

  # Maximum length for the title
  max_length=$(echo $horizontal_size | xargs -I _ echo "_ / $scale_rate" | bc -l | cut -d '.' -f 1)

  if [ ${#text} -gt $max_length ]; then
    trimmed_title="${text:0:$max_length}..."
  else
    trimmed_title="$text"
  fi

  echo "$trimmed_title"
}

get_title() {
  echo "$(playerctl -p spotify metadata --format '{{ title }}')"
}

case $1 in
  show)
    case "$2" in
      trimmed) trim "$(get_title)";;
      *) get_title;;
    esac
    ;;
  previous)
    playerctl -p spotify previous &
    ;;
  next)
    playerctl -p spotify next &
    ;;
  pause)
    playerctl --all-players pause &
    ;;
  play)
    playerctl -p spotify play &
    ;;
  toggle)
    case $(playerctl --all-players status | grep "Playing" | head -n 1) in
      "Playing") playerctl --all-players pause ;;
      *) playerctl -p spotify play ;;
    esac
    ;;
esac
