#!/usr/bin/bash

HOSTNAME=$(hostname -s)

primary=$(polybar -m | grep primary | sed -e 's/:.*$//g')

MONITOR=$monitor polybar top -c "$HOME/dotfiles/linux/config/polybar/bars.ini" &
MONITOR=$monitor polybar stats -c "$HOME/dotfiles/linux/config/polybar/bars.ini"
