#!/usr/bin/bash

CACHE_DIR='/tmp/quotes'
DATE=$(date | sed 's/T.*//')
CACHE_FILE=$CACHE_DIR/$DATE

mkdir -p $CACHE_DIR

get_quote() {
  if [[ ! -f $CACHE_FILE ]]; then
    local request=$(curl -Ls "https://quotes.rest/qod.json?category=inspire")
    $(echo $request | jq -r '.contents.quotes[0].quote' > $CACHE_FILE)
  fi

  echo $(cat $CACHE_FILE)
}

case $1 in
  get) echo `get_quote` ;;
esac
