#!/usr/bin/bash

ICON=$FONT_AWESOME_PATH/light/print.svg

show() {
  notify-send -a Printers \
              -i $ICON \
              -h string:wired-tag:printers \
              "Printers" "$1"
}

show "Searching network..."

IP=$(avahi-browse -t -d local -c -a --resolve | sed -n '/^=.*Printer/,/txt =/p' | head -n 5 | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}')

if [[ -z $IP ]]; then
  show "Not found"
  exit 1
fi

show "Found on $IP"

lpadmin -p epson -E -v ipp://$IP/ipp/print -m everywhere

show "Registered as 'epson'"
