#!/bin/bash

function turn_on {
  amixer -D pulse set Master on > /dev/null
}

function get {
  amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
  amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function show {
  volume=`get`
  bar=$(seq -s "─" $(($volume / 5)) | sed 's/[0-9]//g')

  notify-send.py -i notification-audio-volume-high \
                 --replaces-process volume \
                 -t 1000 \
                 "Volume" "$volume% $bar"
}

case $1 in
  up)
    turn_on
    amixer -D pulse sset Master 2%+ > /dev/null
    show
    ;;
  down)
    turn_on
    amixer -D pulse sset Master 2%- > /dev/null
    show
    ;;
  show) show ;;
  toggle)
    amixer -D pulse set Master 1+ toggle > /dev/null
    if is_mute ; then
      notify-send.py -i notification-audio-volume-muted \
                     --replaces-process volume \
                     -t 1000 \
                     "Volume" "Mute"
    else
      show
    fi
    ;;
esac
