#!/bin/bash

function turn_on {
  amixer -D pulse set Master on > /dev/null
}

function get {
  amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
  amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function show {
  volume=`get`
  bar=$(seq -s "─" $(($volume / 4)) | sed 's/[0-9]//g')

  dunstify -i notification-audio-volume-high \
           -r 12 \
           -u low \
           -a Volume \
           "$volume%" "$bar"
}

case $1 in
  up)
    turn_on
    amixer -D pulse sset Master 2%+ > /dev/null
    show
    ;;
  down)
    turn_on
    amixer -D pulse sset Master 2%- > /dev/null
    show
    ;;
  show) show ;;
  toggle)
    amixer -D pulse set Master 1+ toggle > /dev/null
    if is_mute ; then
      dunstify -i notification-audio-volume-muted \
               -r 12 \
               -u low \
               -a Volume \
               "0%" "Mute"
    else
      show
    fi
    ;;
esac
