#!/bin/bash

function get_volume {
  amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
  amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function show_volume {
  volume=`get_volume`
  bar=$(seq -s "─" $(($volume / 5)) | sed 's/[0-9]//g')

  dunstify -i notification-audio-volume-high -t 1000 -r 24 "Volume" "$volume% $bar"
}

case $1 in
  up)
    amixer -D pulse set Master on > /dev/null
    amixer -D pulse sset Master 2%+ > /dev/null
    show_volume
    ;;
  down)
    amixer -D pulse set Master on > /dev/null
    amixer -D pulse sset Master 2%- > /dev/null
    show_volume
    ;;
  show)
    show_volume
    ;;
  toggle)
    amixer -D pulse set Master 1+ toggle > /dev/null
    if is_mute ; then
      dunstify -i notification-audio-volume-muted -t 1000 -r 24 "Volume" "Mute"
    else
      show_volume
    fi
    ;;
esac
