#!/bin/bash

info=$(sudo nordvpn status)
tatus=$(echo "$info" | grep Status | awk '{print $4}')
summary=$(echo "$info" | grep -vE "(Status|server|tech|protocol)")

dunstify -i globe \
         -r 22 \
         -u normal \
         -a NordVPN \
         "$tatus" "$summary"
