#!/bin/bash

info=$(sudo nordvpn status)
tatus=$(echo "$info" | grep Status | awk '{print $4}')
summary=$(echo "$info" | grep -vE "(Status|server|tech|protocol)")

notify-send -a NordVPN \
            -i ~/dotfiles/fonts/fa6/pngs/light/globe.png \
            -h string:wired-tag:usb \
            "$tatus" "$summary"
