#!/usr/bin/bash

WALLPAPER_PATH="$HOME/wallpaper.png"

case $1 in
  load)
    xwallpaper --zoom "$WALLPAPER_PATH";;
  update|change)
    rm -rf "$WALLPAPER_PATH"
    ln -fvs "$2" "$WALLPAPER_PATH"
    $0 load;;
  random)
    $0 change `find $2 -maxdepth 1 -type f | shuf -n 1`
esac
