#!/usr/bin/bash

set -eu

source "$HOME/dotfiles/linux/variables.env"

declare -A ICON_LIST=(
  ["01d"]="" # Clear sky day
  ["01n"]="" # Clear sky night.
  ["02d"]="" # Few clouds day.
  ["02n"]="" # Few clouds night.
  ["03d"]="" # Scattered clouds day.
  ["03n"]="" # Scattered clouds night.
  ["04d"]="" # Broken clouds day.
  ["04n"]="" # Broken clouds night.
  ["09d"]="" # Shower rain day.
  ["09n"]="" # Shower rain night.
  ["10d"]="" # Rain day.
  ["10n"]="" # Rain night
  ["11d"]="" # Thunderstorm day.
  ["11n"]="" # Thunderstorm night
  ["13d"]="" # Snow day. Snowflake alternative: 
  ["13n"]="" # Snow night. Snowflake alternative: 
  ["50d"]="" # Mist day.
  ["50n"]="" # Mist night.
  ["null"]="" # missing
)

SYSTEM="metric" # Unit system {imperial or metric}
UNIT="°C" # Units of measurement.

LOCATION_DATA=$(curl -Ls http://ipwho.is)
CITY=$(echo $LOCATION_DATA | jq -r .city)

FORECAST=$(
  curl -Ls --get \
    --data-urlencode "q=$CITY" \
    --data-urlencode "units=$SYSTEM" \
    --data-urlencode "appid=$OPEN_WEATHER_API_KEY" \
    "http://api.openweathermap.org/data/2.5/weather"
)
ICON=${ICON_LIST[$(echo $FORECAST | jq -r '.weather[0].icon')]}

function show {
  SUMMARY=$(echo $FORECAST | jq -r '.weather[0].main')
  TEMP=$(echo $FORECAST | jq -r '.main.temp')
  DESCRIPTION=$(cat <<- EOM
Minimum: $(echo $FORECAST | jq -r '.main.temp_min')$UNIT
Maximun: $(echo $FORECAST | jq -r '.main.temp_max')$UNIT
Feels Like: $(echo $FORECAST | jq -r '.main.feels_like')$UNIT
Humidity: $(echo $FORECAST | jq -r '.main.humidity')%
Location: $(echo $FORECAST | jq -r '"\(.name) - \(.sys.country)"')
EOM
)
  notify-send -a Info \
              -i "$FONT_AWESOME_PATH/light/cloud-bolt-sun.svg" \
              -h string:wired-tag:info \
              -t 10000 \
              "$SUMMARY $TEMP$UNIT" "$DESCRIPTION"
}

case $1 in
  icon) echo $ICON;;
  show) show
esac
