#!/usr/bin/bash

declare -A ICON_LIST=(
  ["01d"]="" # Clear sky day
  ["01n"]="" # Clear sky night.
  ["02d"]="" # Few clouds day.
  ["02n"]="" # Few clouds night.
  ["03d"]="" # Scattered clouds day.
  ["03n"]="" # Scattered clouds night.
  ["04d"]="" # Broken clouds day.
  ["04n"]="" # Broken clouds night.
  ["09d"]="" # Shower rain day.
  ["09n"]="" # Shower rain night.
  ["10d"]="" # Rain day.
  ["10n"]="" # Rain night
  ["11d"]="" # Thunderstorm day.
  ["11n"]="" # Thunderstorm night
  ["13d"]="" # Snow day. Snowflake alternative: 
  ["13n"]="" # Snow night. Snowflake alternative: 
  ["50d"]="" # Mist day.
  ["50n"]="" # Mist night.
)

API_KEY=$OPEN_WEATHER_API_KEY
UNITS="metric" # Unit system {imperial or metric}
UNIT="°C" # Units of measurement. That will be showed in UI. Does not affect on API.

IP=$(curl -s https://ipinfo.io/ip)
CITY=$(curl -s https://freegeoip.app/json/$IP | jq -r .city)

FORECAST=$(curl -s "http://api.openweathermap.org/data/2.5/weather?q=$CITY&units=$UNITS&appid=$API_KEY")
ICON=${ICON_LIST[$(echo $FORECAST | jq -r '.weather[0].icon')]}

function show {
  SUMMARY=$(echo $FORECAST | jq -r '.weather[0].main')
  TEMP=$(echo $FORECAST | jq -r '.main.temp')
  DESCRIPTION=$(cat <<- EOM
Minimum: $(echo $FORECAST | jq -r '.main.temp_min')$UNIT
Maximun: $(echo $FORECAST | jq -r '.main.temp_max')$UNIT
Feels Like: $(echo $FORECAST | jq -r '.main.feels_like')$UNIT
Humidity: $(echo $FORECAST | jq -r '.main.humidity')%
Location: $(echo $FORECAST | jq -r '"\(.name) - \(.sys.country)"')
EOM
)
  notify-send -a System \
              -i ~/dotfiles/fonts/fa6/svgs/light/sun.svg \
              -h string:wired-tag:system \
              "$SUMMARY $TEMP$UNIT" "$DESCRIPTION"
}

case $1 in
  print) echo $ICON;;
  show) `show`
esac
