#!/usr/bin/bash

set -eu

source "$HOME/dotfiles/linux/variables.env"

declare -A ICON_LIST=(
  ["01d"]="󰖙"
  ["01n"]="󰖔"
  ["02d"]="󰖕"
  ["02n"]="󰼱"
  ["03d"]="󰖐"
  ["03n"]="󰖐"
  ["04d"]="󰖐"
  ["04n"]="󰖐"
  ["09d"]="󰖖"
  ["09n"]="󰖖"
  ["10d"]="󰖗"
  ["10n"]="󰖗"
  ["11d"]="󰖓"
  ["11n"]="󰖓"
  ["13d"]="󰖘"
  ["13n"]="󰖘"
  ["50d"]="󰖑"
  ["50n"]="󰖑"
  ["null"]="󰖐"
)

SYSTEM="metric" # Unit system {imperial or metric}
UNIT="°C" # Units of measurement.

LOCATION_DATA=$(curl --fail --silent --show-error --connect-timeout 5 --max-time 10 https://ipwho.is)
CITY=$(jq -er '.city' <<< "$LOCATION_DATA")

FORECAST=$(
  curl --fail --silent --show-error --connect-timeout 5 --max-time 10 --get \
    --data-urlencode "q=$CITY" \
    --data-urlencode "units=$SYSTEM" \
    --data-urlencode "appid=$OPEN_WEATHER_API_KEY" \
    "https://api.openweathermap.org/data/2.5/weather"
)
ICON=${ICON_LIST[$(jq -er '.weather[0].icon' <<< "$FORECAST")]}

function show {
  SUMMARY=$(jq -er '.weather[0].main' <<< "$FORECAST")
  TEMP=$(jq -er '.main.temp' <<< "$FORECAST")
  DESCRIPTION=$(cat <<- EOM
Minimum: $(echo "$FORECAST" | jq -r '.main.temp_min')$UNIT
Maximun: $(echo "$FORECAST" | jq -r '.main.temp_max')$UNIT
Feels Like: $(echo "$FORECAST" | jq -r '.main.feels_like')$UNIT
Humidity: $(echo "$FORECAST" | jq -r '.main.humidity')%
Location: $(echo "$FORECAST" | jq -r '"\(.name) - \(.sys.country)"')
EOM
  )
  notify-send -a Info \
    -i "$LUCIDE_PATH/cloud-lightning.svg" \
    -h string:wired-tag:info \
    -t 10000 \
    "$SUMMARY $TEMP$UNIT" "$DESCRIPTION" 2> /dev/null || true
}

case $1 in
  icon) echo "$ICON" ;;
  show) show
esac
