# For screensharing. See https://wiki.hyprland.org/Useful-Utilities/Screen-Sharing/#xwayland
windowrule {
  name = windowrule-13
  opacity = 0.0 override
  no_anim = on
  no_initial_focus = on
  max_size = 1 1
  no_blur = on
  match:class = ^(xwaylandvideobridge)$
}
