bindkey -e

source "$HOME/dotfiles/linux/variables.env"

source "$DOTFILES/linux/config/zsh/theme.zsh"
source "$DOTFILES/linux/config/zsh/history.zsh"
source "$DOTFILES/linux/config/zsh/doc-search.zsh"
source "$DOTFILES/linux/config/zsh/projects.zsh"
source "$DOTFILES/linux/config/zsh/work.zsh"

bindkey "^[[1;5C" forward-word      # Ctrl+right
bindkey "^[[1;5D" backward-word     # Ctrl+left
bindkey "^[[H"    beginning-of-line # Ctrl+a
bindkey "^[[F"    end-of-line       # Ctrl+e
bindkey "^[[3~"   delete-char       # delete

autoload -U select-word-style
select-word-style bash

# case insensitive autocompletion
autoload -Uz compinit && compinit
bindkey -M menuselect '^[[Z' reverse-menu-complete
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

autoload edit-command-line
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

bindkey '^H' backward-kill-word
bindkey '\e[3;5~' kill-word

if [[ "$(uname)" == "Linux" ]]; then
    source "$DOTFILES/linux/env"
fi
