set nocompatible
filetype off

syntax on

" remap 0 in normal mode to go to the beginning of the text line
nmap 0 ^
nmap - ^

" Automatically wrap at 72 characters and spell check git commit messages
autocmd FileType gitcommit setlocal textwidth=72
autocmd FileType gitcommit setlocal spell
" enable word autocompletion
set complete+=kspell

au BufRead,BufNewFile *.md setlocal spell
au BufRead,BufNewFile .env.* setfiletype sh

command! PrettyPrintJSON %!python -m json.tool
command! PrettyPrintHTML !tidy -mi -html -wrap 0 %
command! PrettyPrintXML !tidy -mi -xml -wrap 0 %
