Section "InputClass"
  Identifier "touchpad"
  Driver "libinput"
  MatchIsTouchpad "on"
  Option "NaturalScrolling" "true"
  Option "Tapping" "on"
EndSection

Section "InputClass"
  Identifier "mouse natural scrolling"
  Driver "libinput"
  MatchIsPointer "on"
  Option "NaturalScrolling" "true"
EndSection
