#!/bin/env ruby

require "json"

def battery(info)
  raw = info["Battery Percentage"].to_s
  match = raw[/\(([^)]+)\)/]
  match ? match[1] : ""
end

devices = `bluetoothctl devices Connected`.lines.filter_map do |line|
  next unless line.start_with?("Device ")

  _tag, uid, *name = line.split

  info = `bluetoothctl info #{uid}`
    .split("\n")
    .map { |entry| entry.split(":", 2).map(&:strip) }
    .select { |key, _val| key == "Name" || key == "Battery Percentage" }
    .to_h

  {
    "uid" => uid,
    "name" => info["Name"] || name.join(" "),
    "battery" => battery(info)
  }
end

puts devices.to_json