#!/bin/env ruby

require "json"
require "date"

HIDE_LIST = [
  "info",
  "spotify",
  "volume",
  "brightness",
  "flameshot",
  "power manager",
  "package manager",
  "networkmanager applet",
  "microphone",
  "notify-send"
].freeze

ICONS = [
  {
    body: /was saved in/,
    icon: "key-skeleton"
  },
  {
    name: "Printers",
    icon: "print"
  },
  {
    name: "Google Chrome",
    icon: "globe"
  },
  {
    name: "Telegram Desktop",
    icon: "messages"
  },
  {
    name: "discord",
    icon: "messages"
  },
  {
    name: "blueman",
    icon: "bluetooth"
  }
].freeze

def enrich(entry)
  entry.merge(
    {
      "icon" => icon_for(entry),
      "app_name" => entry.fetch("app_name").capitalize,
      "timestamp" => Time.at(entry.fetch("time")).strftime("%m/%d %H:%M")
    }
  )
end

def icon_for(entry)
  ICONS.find do |i|
    (i[:name] == entry.fetch("app_name")) ||
      i[:body]&.match?(entry.fetch("body"))
  end&.fetch(:icon, "bell")
end

puts `cat /tmp/wired.log`
  .split("\n")
  .map { |entry| JSON.parse(entry) }
  .select { |entry| (entry.values_at("app_name", "summary").map(&:downcase) & HIDE_LIST).empty? }
  .sort { |entry, _| entry.fetch("time") }
  .first(25)
  .map(&method(:enrich))
  .to_json
