#!/usr/bin/bash

source "$HOME/dotfiles/unix/setup/aliases"
source "$HOME/dotfiles/unix/setup/configs"
source "$HOME/dotfiles/unix/setup/git-config"

source "$HOME/dotfiles/osx/setup/aliases"
source "$HOME/dotfiles/osx/setup/dependencies"
source "$HOME/dotfiles/osx/setup/configs"
