#!/usr/bin/bash

set -eu

source "$HOME/dotfiles/linux/variables.env"

u_wallpaper load &> /dev/null

notify-send -a System \
            -i "$LUCIDE_PATH/monitor.svg" \
            -h string:wired-tag:system \
            "\"$AUTORANDR_CURRENT_PROFILE\""
