#!/usr/bin/bash

set -eu

source "$HOME/dotfiles/linux/variables.env"

u_wallpaper load &> /dev/null
polybar-msg cmd restart &> /dev/null

notify-send -a System \
            -i "$FONT_AWESOME_PATH/light/display.svg" \
            -h string:wired-tag:system \
            "\"$AUTORANDR_CURRENT_PROFILE\""
