#!/usr/bin/bash

set -e

u_wallpaper load 1> /dev/null
polybar-msg cmd restart 1> /dev/null

notify-send -a System \
            -i "$FONT_AWESOME_PATH/light/display.svg" \
            -h string:wired-tag:system \
            "\"$AUTORANDR_CURRENT_PROFILE\""
