#!/usr/bin/bash

export TZ='Europe/Copenhagen'
export TERMINFO='/usr/share/terminfo'
export TERM=xterm-kitty
export XDG_CONFIG_HOME="$HOME/.config"
export DOTFILES="$HOME/dotfiles"
export KITTY_CONFIG_DIRECTORY="$DOTFILES/linux/config/"
export BROWSER=/usr/bin/google-chrome-stable
export BAT_PAGER='less -RFI'
export FZF_DEFAULT_OPTS="--layout=reverse --border --header 'Ctrl+d: PageUp / Ctrl+l: PageDown' --bind ctrl-l:page-down,ctrl-h:page-up"

if [[ -z $(echo $SSH_AUTH_SOCK) ]]; then
  eval `ssh-agent -s` > /dev/null
  ssh-add "$HOME/.ssh/id_ed25519" 2> /dev/null
fi

if test -f "$HOME/.cargo/env"; then
  source "$HOME/.cargo/env"
fi
