#!/bin/bash

eval `ssh-agent -s`

export TZ='Europe/Copenhagen'
export QT_QPA_PLATFORMTHEME="qt5ct"
export EDITOR=nvim
export TERM=kitty
export XDG_CONFIG_HOME="$HOME/.config"
export KITTY_CONFIG_DIRECTORY=~/dotfiles/linux/config/
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export BROWSER=/usr/bin/google-chrome-stable
export FZF_DEFAULT_COMMAND="ag -l '.*' --ignore=qa"
