#!/usr/bin/bash

export DOTFILES="$HOME/dotfiles"
export XDG_CONFIG_HOME="$HOME/.config"

export TZ='Europe/Copenhagen'

export TERMINFO='/usr/share/terminfo'
export TERM="xterm-kitty"
export KITTY_CONFIG_DIRECTORY="$DOTFILES/linux/config/"
export BAT_PAGER='less -RFI'
export MANPAGER='nvim +Man!'
export FZF_DEFAULT_OPTS="--layout=reverse --border --header 'Ctrl+h: PageDown / Ctrl+l: PageUp' --bind ctrl-h:page-down,ctrl-l:page-up"

export EDITOR='nvim'
export BROWSER=/usr/bin/google-chrome-stable
export QT_QPA_PLATFORMTHEME="qt5ct"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export FONT_AWESOME_PATH="$DOTFILES/fonts/fa6/svgs"
