#!/usr/bin/bash

export XDG_SESSION_TYPE="x11"
export XDG_SESSION_DESKTOP="$1"

userresources=$HOME/.Xresources
xprofile=$DOTFILES/linux/xprofile
sysresources=/etc/X11/xinit/.Xresources
environment=$DOTFILES/linux/env

if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

source "$environment"

if [ -f "$xprofile" ]; then
  source "$xprofile"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && source "$f"
  done
  unset f
fi

if [[ -z $(echo $SSH_AUTH_SOCK) ]]; then
  eval `ssh-agent -s` > /dev/null
  ssh-add "$HOME/.ssh/id_ed25519" 2> /dev/null
fi

case "$1" in
  awesome) exec awesome ;;
  bspwm) exec bspwm-session ;;
  i3|i3wm|*) exec dbus-run-session -- i3 ;;
esac
