#!/usr/bin/bash

userresources=$HOME/.Xresources
xprofile=$HOME/dotfiles/linux/xprofile
sysresources=/etc/X11/xinit/.Xresources
environment=$HOME/dotfiles/linux/env
default_session='i3 --shmlog-size 0'

# merge in defaults and keymaps
if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

source $environment

if [ -f $xprofile ]; then
  source $xprofile
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && source "$f"
  done
  unset f
fi

if [[ -z $(echo $SSH_AUTH_SOCK) ]]; then
  eval `ssh-agent -s` > /dev/null
  ssh-add ~/.ssh/id_ed25519 2> /dev/null
fi

get_session(){
  local dbus_args=(--sh-syntax --exit-with-session)
  case $1 in
    awesome) dbus_args+=(awesome) ;;
    bspwm) dbus_args+=(bspwm-session) ;;
    deepin) dbus_args+=(startdde) ;;
    hypr) dbus_args+=(Hypr) ;;
    i3|i3wm) dbus_args+=($default_session) ;;
    *) dbus_args+=($default_session) ;;
  esac
  echo "dbus-launch ${dbus_args[*]}"
}
exec $(get_session "$1")
