#!/bin/sh

# keyboard configs
xset r rate 200 35
setxkbmap -layout us -variant mac
xmodmap ~/dotfiles/linux/config/keyboard.map && touch ~/xmodmap-ran

# identify and set monitor profiles
autorandr --change

# set wallpaper
xwallpaper --zoom ~/wallpaper.png &

export PATH="$HOME/dotfiles/linux/bin:$PATH"

. ~/Dropbox/secrets
. ~/dotfiles/linux/config/autostart
