#!/usr/bin/env sh

# keyboard configs
xset r rate 200 35
setxkbmap -layout us -variant mac
xmodmap ~/dotfiles/linux/config/keyboard.map

# identify and set monitor profiles
autorandr --change

# set wallpaper
xwallpaper --zoom ~/wallpaper.png &

export QT_QPA_PLATFORMTHEME="qt5ct"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

source ~/Dropbox/secrets
source ~/dotfiles/linux/config/autostart
