source ~/dotfiles/unix/config/zsh/theme.zsh
source ~/dotfiles/unix/config/zsh/functions.zsh
source ~/dotfiles/unix/config/zsh/work.zsh

# history settings
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt EXTENDED_HISTORY
setopt HIST_SAVE_NO_DUPS

bindkey -e

# use Ctrl for word navigation
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "^[[3~"   delete-char
bindkey "^[[H"    beginning-of-line
bindkey "^[[F"    end-of-line

bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# case insensitive autocompletion
autoload -Uz compinit && compinit
bindkey -M menuselect '^[[Z' reverse-menu-complete
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

source ~/dotfiles/unix/env
if [[ "$(uname)" == "Linux" ]]; then
  source ~/dotfiles/linux/env
fi
